# Generated by Django 4.2.4 on 2023-08-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userIdConnect', models.IntegerField()),
                ('noteTitle', models.CharField(max_length=50)),
                ('textNote', models.TextField()),
                ('noteColor', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=35)),
                ('userPass', models.CharField(max_length=35)),
            ],
        ),
    ]
